---
apiVersion: v1
kind: Service
metadata:
  annotations:
    fabric8.io/git-commit: 2f0f7289e44e5a7d633b411cf5578fe3e91d299c
    fabric8.io/iconUrl: img/icons/camel.svg
    fabric8.io/git-branch: master
    prometheus.io/scrape: "true"
    prometheus.io/port: "9779"
  labels:
    expose: "true"
    app: api1
    provider: fabric8
    version: 1.0-SNAPSHOT
    group: com.test.consulting
  name: api1
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: api1
    provider: fabric8
    group: com.test.consulting
